name: DCO

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dco:
    name: DCO
    runs-on: ubuntu-24.04
    steps:
      - name: Check DCO sign-off
        uses: KineticCafe/actions-dco@5f160e3ee086af8fc0fb567b8add0937d074123e # v3.2.0
        with:
          config: |
            bot.policy = "allowlist"
            bot.allow = ["dependabot[bot]"]

            [alias-signoffs.aliases]
            "49699333+dependabot[bot]@users.noreply.github.com" = ["support@github.com"]
